from django.conf.urls import patterns, include, url

from django.contrib import admin

from django.views.generic import TemplateView 
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'csvt01.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index.html$','blog.views.index'),
    url(r'^loginout/$', 'blog.views.loginout'),

    url(r'^$','blog.views.login'),
      

    url(r'^accounts/login/$', 'blog.views.login'),  
    url(r'^www.html$','blog.views.www'),
	url(r'^app.html$','blog.views.app'),
	url(r'^client.html$','blog.views.client'),
#	url(r'^i.html$','blog.views.i'),
	url(r'^item.html$','blog.views.item'),
	url(r'^search.html$','blog.views.search'),
	url(r'^service.html$','blog.views.service'),
	url(r'^tejia.html$','blog.views.tejia'),
	url(r'^tuan.html$','blog.views.tuan'),
        url(r'^control.html$','blog.views.control'),
	url(r'^br.html$','blog.views.br'),
	url(r'^recom.html$','blog.views.recom'),
	url(r'^showmold.html$','blog.views.showmold'),
	url(r'^showapp.html$','blog.views.showapp'),
    url(r'^showeng.html$','blog.views.showeng'),
    url(r'^sitemap.html$','blog.views.sitemap'),
    url(r'^dapei.html$','blog.views.dapei'),
	url(r'^regist.html$','blog.views.regist'),
        url(r'^mem.html$',TemplateView.as_view(template_name="mem.html")),
	url(r'^register.html$','blog.views.register'),
        url(r'^zzbs.html$',TemplateView.as_view(template_name="auto/zzbs.html")),
	url(r'^autowww.html$','blog.views.autowww'),
        url(r'^depwww121.html$','blog.views.depwww121'),
        url(r'^depwww80.html$','blog.views.depwww80'),
        url(r'^depwww81.html$','blog.views.depwww81'),
        url(r'^dep-app121.html$','blog.views.depapp121'),
        url(r'^dep-app186.html$','blog.views.depapp186'),
        url(r'^dep-app22.html$','blog.views.depapp22'),
        url(r'^zzbs-app.html$',TemplateView.as_view(template_name="auto/zzbs-app.html")),
        url(r'^register-app.html$','blog.views.registerapp'),
        url(r'^auto-app.html$','blog.views.autoapp'),

        url(r'^dep-client186.html$','blog.views.depclient186'),
        url(r'^dep-client22.html$','blog.views.depclient22'),
        url(r'^dep-client183.html$','blog.views.depclient183'),
        url(r'^dep-client51.html$','blog.views.depclient51'),
        url(r'^zzbs-client.html$','blog.views.zzbsclient'),
        url(r'^register-client.html$','blog.views.registerclient'),
        url(r'^auto-client.html$','blog.views.autoclient'),

 #       url(r'^dep-i121.html$','blog.views.depi121'),
 #       url(r'^dep-i22.html$','blog.views.depi22'),
 #       url(r'^zzbs-i.html$','blog.views.zzbsi'),
 #       url(r'^register-i.html$','blog.views.registeri'),
 #       url(r'^auto-i.html$','blog.views.autoi'),

        url(r'^dep-item59.html$','blog.views.depitem59'),
        url(r'^dep-item17.html$','blog.views.depitem17'),
        url(r'^dep-item37.html$','blog.views.depitem37'),
        url(r'^zzbs-item.html$','blog.views.zzbsitem'),
        url(r'^register-item.html$','blog.views.registeritem'),
        url(r'^auto-item.html$','blog.views.autoitem'),

        url(r'^dep-search17.html$','blog.views.depsearch17'),
        url(r'^dep-search37.html$','blog.views.depsearch37'),
        url(r'^zzbs-search.html$','blog.views.zzbssearch'),
        url(r'^register-search.html$','blog.views.registersearch'),
        url(r'^auto-search.html$','blog.views.autosearch'),

        url(r'^dep-service22.html$','blog.views.depservice22'),
        url(r'^dep-service52.html$','blog.views.depservice52'),
        url(r'^dep-service59.html$','blog.views.depservice59'),
        url(r'^zzbs-service.html$','blog.views.zzbsservice'),
        url(r'^register-service.html$','blog.views.registerservice'),
        url(r'^auto-service.html$','blog.views.autoservice'),

        url(r'^dep-tejia19.html$','blog.views.deptejia19'),
        url(r'^dep-tejia18.html$','blog.views.deptejia18'),
        url(r'^zzbs-tejia.html$','blog.views.zzbstejia'),
        url(r'^register-tejia.html$','blog.views.registertejia'),
        url(r'^auto-tejia.html$','blog.views.autotejia'),

        url(r'^dep-tuan19.html$','blog.views.deptuan19'),
        url(r'^dep-tuan18.html$','blog.views.deptuan18'),
        url(r'^zzbs-tuan.html$','blog.views.zzbstuan'),
        url(r'^register-tuan.html$','blog.views.registertuan'),
        url(r'^auto-tuan.html$','blog.views.autotuan'),

        url(r'^dep-sitemap80.html$','blog.views.depsitemap80'),
        url(r'^dep-sitemap83.html$','blog.views.depsitemap83'),
        url(r'^zzbs-sitemap.html$','blog.views.zzbssitemap'),
        url(r'^register-sitemap.html$','blog.views.registersitemap'),
        url(r'^auto-sitemap.html$','blog.views.autositemap'),
      
        url(r'^dep-dapei106.html$','blog.views.depdapei106'),
        url(r'^dep-dapei37.html$','blog.views.depdapei37'),
        url(r'^dep-dapei80.html$','blog.views.depdapei80'),
        url(r'^zzbs-dapei.html$','blog.views.zzbsdapei'),
        url(r'^register-dapei.html$','blog.views.registerdapei'),
        url(r'^auto-dapei.html$','blog.views.autodapei'),

##################################zhuzhan_log################################
        url(r'^log_index.html$','blog.views.logindex'),
#        url(r'^log-www-121.html$','blog.views.wwwlog121'),
#        url(r'^log-www-80.html$','blog.views.wwwlog80'),
#        url(r'^log-www-81.html$','blog.views.wwwlog81'),
#        url(r'^log-app-121.html$','blog.views.applog121'),
#        url(r'^log-app-186.html$','blog.views.applog186'),
#        url(r'^log-app-22.html$','blog.views.applog22'),
#        url(r'^log-i-121.html$','blog.views.ilog121'),
#        url(r'^log-i-22.html$','blog.views.ilog22'),
#        url(r'^log-item-59.html$','blog.views.itemlog59'),
#        url(r'^log-item-17.html$','blog.views.itemlog17'),
#        url(r'^log-item-37.html$','blog.views.itemlog37'),
#        url(r'^log-search-37.html$','blog.views.searchlog37'),
#        url(r'^log-search-17.html$','blog.views.searchlog17'),
#        url(r'^log-service-22.html$','blog.views.servicelog22'),
#        url(r'^log-service-52.html$','blog.views.servicelog52'),
#        url(r'^log-service-59.html$','blog.views.servicelog59'),
#        url(r'^log-tejia-18.html$','blog.views.tejialog18'),
#        url(r'^log-tejia-19.html$','blog.views.tejialog19'),
#        url(r'^log-tuan-18.html$','blog.views.tuanlog18'),
#        url(r'^log-tuan-19.html$','blog.views.tuanlog19'),
#        url(r'^log-sitemap-80.html$','blog.views.sitemaplog80'),
#        url(r'^log-sitemap-83.html$','blog.views.sitemaplog83'),
#        url(r'^log-dapei-106.html$','blog.views.dapeilog106'),
#        url(r'^log-dapei-37.html$','blog.views.dapeilog37'),
#        url(r'^log-dapei-80.html$','blog.views.dapeilog80'),
#        url(r'^log-control-18.html$','blog.views.controllog18'),
#        url(r'^log-control-19.html$','blog.views.controllog19'),
##############################bijia_log###################################
        url(r'^log_index1.html$','blog.views.logindex1'),
#        url(r'^log-bijia183_1.html$','blog.views.bijia183_1'),
#        url(r'^log-bijia183_2.html$','blog.views.bijia183_2'),
#        url(r'^log-bijia183_3.html$','blog.views.bijia183_3'),
#	url(r'^log-bijia183_4.html$','blog.views.bijia183_4'),
#        url(r'^log-bijia94_1.html$','blog.views.bijia94_1'),
#        url(r'^log-bijia94_2.html$','blog.views.bijia94_2'),
#        url(r'^log-bijia94_3.html$','blog.views.bijia94_3'),
#        url(r'^log-bijia83_1.html$','blog.views.bijia83_1'),
#        url(r'^log-bijia83_2.html$','blog.views.bijia83_2'),
#        url(r'^log-bijia83_3.html$','blog.views.bijia83_3'),
#        url(r'^log-bijia48_1.html$','blog.views.bijia48_1'),
#        url(r'^log-bijia48_2.html$','blog.views.bijia48_2'),
#        url(r'^log-bijia48_3.html$','blog.views.bijia48_3'),
#        url(r'^log-bijia51_1.html$','blog.views.bijia51_1'),
#        url(r'^log-bijia51_2.html$','blog.views.bijia51_2'),
#        url(r'^log-bijia51_3.html$','blog.views.bijia51_3'),
#        url(r'^log-recom51_1.html$','blog.views.recom51_1'),
#        url(r'^log-recom51_2.html$','blog.views.recom51_2'),
#        url(r'^log-recom51_3.html$','blog.views.recom51_3'),
#        url(r'^log-recom23_1.html$','blog.views.recom23_1'),
#        url(r'^log-recom23_2.html$','blog.views.recom23_2'),
#        url(r'^log-recom23_3.html$','blog.views.recom23_3'),
#	url(r'^log-client-186.html$','blog.views.bijiacs186_1'),
#        url(r'^log-client-22.html$','blog.views.bijiacs22_1'),
#        url(r'^log-bijiacs183_1.html$','blog.views.bijiacs183_1'),
#        url(r'^log-bijiacs51_1.html$','blog.views.bijiacs51_1'),
#########################################################################
      #  url(r'^register-bijiadep.html$','blog.views.registerbijiadep'),
      #  url(r'^bijia-auto.html$','blog.views.bijiadep_auto'),
      #  url(r'^depbrowser183.html$','blog.views.bijiadep_183'),
      #  url(r'^depbrowser23.html$','blog.views.bijiadep_23'),
      #  url(r'^register-bijiadep.html$','blog.views.registerbijiadep'),
      #  url(r'^zzbs-bijiadep.html$','blog.views.zzbsbijiadep'),
      #  #url(r'^log-bijia.html$','blog.views.bijiadep_auto'),
      #  url(r'^depbrowser183.html$','blog.views.bijiadep_183'),
      #  url(r'^depbrowser94.html$','blog.views.bijiadep_94'),
      #  url(r'^depbrowser83.html$','blog.views.bijiadep_83'),
      #  url(r'^depbrowser48.html$','blog.views.bijiadep_48'),
      #  url(r'^depbrowser51.html$','blog.views.bijiadep_51'),
      #  #url(r'^depbrowser23.html$','blog.views.bijiadep_23'),
      #  url(r'^depbrowser183w.html$','blog.views.bijiadep_183_wc'),
      #  url(r'^depbrowser94w.html$','blog.views.bijiadep_94_wc'),
      #  url(r'^depbrowser83w.html$','blog.views.bijiadep_83_wc'),
      #  url(r'^depbrowser48w.html$','blog.views.bijiadep_48_wc'),
      #  url(r'^depbrowser51w.html$','blog.views.bijiadep_51_wc'),
      #  #url(r'^depbrowser23w.html$','blog.views.bijiadep_23_wc'),
#########################################################################
        url(r'^register-recomdep.html$','blog.views.registerrecomdep'),
        url(r'^zzbs-recomdep.html$','blog.views.zzbsrecomdep'),
    #    url(r'^recom-auto.html$','blog.views.recomdep_auto'),
        url(r'^deprecom23.html$','blog.views.recomdep_23'),
	url(r'^deprecom51.html$','blog.views.recomdep_51'),
     #   url(r'^deprecom23w.html$','blog.views.recomdep_23_wc'),
#	url(r'^deprecom51w.html$','blog.views.recomdep_51_wc'),
  #      url(r'^recomdepdel.html$','blog.views.recomdepdel'),
#####################################################################
        url(r'^dep-control18.html$','blog.views.controldep_18'),
        url(r'^dep-control19.html$','blog.views.controldep_19'),
        url(r'^zzbs-control.html$','blog.views.zzbscontroldep'),
        url(r'^register-control.html$','blog.views.registercontroldep'),
        url(r'^auto-control.html$','blog.views.controldep_auto'),
########################################################################
        url(r'^dep-qdtmt.html$','blog.views.registerqdtmtdep'),
        url(r'^zzbs-tmt.html$','blog.views.zzbstmtdep'),
        url(r'^dep-qdtmtdep_13.html$','blog.views.qdtmtdep_13'),
	url(r'^dep-qdtmtdep_118.html$','blog.views.qdtmtdep_118'),

        url(r'^dep-qdtaobao.html$','blog.views.registerqdtaobaodep'),
        url(r'^dep-qdtaobaodep_13.html$','blog.views.qdtaobaodep_13'),
	url(r'^dep-qdtaobaodep_118.html$','blog.views.qdtaobaodep_118'),
        url(r'^zzbs-taobao.html$','blog.views.zzbstaobaodep'),


        url(r'^dep-qdqdstat.html$','blog.views.registerqdqdstatdep'),
        url(r'^dep-qdqdstatdep_86.html$','blog.views.qdqdstatdep_86'),
        url(r'^dep-qdqdstatdep_7.html$','blog.views.qdqdstatdep_7'),
        url(r'^zzbs-qdstat.html$','blog.views.zzbsqdstatdep'),
        url(r'^cdn_qdstat_post.html$','blog.views.cdn_qdstat_post'),

        url(r'^dep-qdchaoji99.html$','blog.views.registerqdchaoji99dep'),
        url(r'^dep-qdchaoji99dep_86.html$','blog.views.qdchaoji99dep_86'),
        url(r'^dep-qdchaoji99dep_7.html$','blog.views.qdchaoji99dep_7'),
        url(r'^zzbs-qdchaoji99.html$','blog.views.zzbchaoji99dep'),
        url(r'^cdn_qdchaoji99_post.html$','blog.views.cdn_qdchaoji99_post'),
######################################################################
        url(r'^dep-cmsproxy.html$','blog.views.registercmsproxydep'),
        url(r'^zzbscmsproxydep.html$','blog.views.zzbscmsproxydep'),
        url(r'^dep-cmsprxoydep_22.html$','blog.views.cmsprxoydep_22'),
        url(r'^dep-cmsprxoydep_23.html$','blog.views.cmsprxoydep_23'),
        url(r'^dep-cmsprxoydep_83.html$','blog.views.cmsprxoydep_83'),
        url(r'^cmsproxy.html$','blog.views.cmsproxy'),
        url(r'^cmsproxydepdel.html$','blog.views.cmsproxydepdel'),
        
        url(r'^dep-cmscp.html$','blog.views.registercmsdep'),
        url(r'^dep-cms.html$','blog.views.registercmsdep'),
        url(r'^zzbs-zzbscmsdep.html$','blog.views.zzbscmsdep'),
        url(r'^cmsdep_121.html$','blog.views.cmsdep_121'),
#########################################################################
        url(r'^registerseckill.html$','blog.views.registerseckill'),
        url(r'^autoseckill.html$','blog.views.autoseckill'),
        url(r'^zzbsseckill.html$','blog.views.zzbsseckill'),
        url(r'^seckilldep_80.html$','blog.views.seckilldep_80'),
        url(r'^seckilldep_81.html$','blog.views.seckilldep_81'),
        url(r'^seckill.html$','blog.views.seckill'),
#######################################################################
        url(r'^registerpay_web.html$','blog.views.registerpay_web'),
        url(r'^autopay_web.html$','blog.views.autopay_web'),
        url(r'^zzbspay_web.html$','blog.views.zzbspay_web'),
        url(r'^pay_webdep_80.html$','blog.views.pay_webdep_80'),
        url(r'^pay_webdep_81.html$','blog.views.pay_webdep_81'),
        url(r'^pay_web.html$','blog.views.pay_web'),
#############################################################################
        url(r'^registertrade_web.html$','blog.views.registertrade_web'),
        url(r'^autotrade_web.html$','blog.views.autotrade_web'),
        url(r'^zzbstrade_web.html$','blog.views.zzbstrade_web'),
        url(r'^trade_webdep_80.html$','blog.views.trade_webdep_80'),
        url(r'^trade_webdep_81.html$','blog.views.trade_webdep_81'),
        url(r'^trade_web.html$','blog.views.trade_web'),
###########################################################################
        url(r'^registertradeback.html$','blog.views.registertradeback'),
        url(r'^autotradeback.html$','blog.views.autotradeback'),
        url(r'^zzbstradeback.html$','blog.views.zzbstradeback'),
        url(r'^tradebackdep_81.html$','blog.views.tradebackdep_81'),
    #    url(r'^tradeback.html$','blog.views.tradeback'),
#############################################################################
        url(r'^registerp4p_mgr.html$','blog.views.registerp4p_mgr'),
        url(r'^autop4p_mgr.html$','blog.views.autop4p_mgr'),
        url(r'^zzbsp4p_mgr.html$','blog.views.zzbsp4p_mgr'),
        url(r'^p4p_mgrdep_11.html$','blog.views.p4p_mgrdep_11'),
        url(r'^p4p_mgr.html$','blog.views.zzbsp4p_mgr'),
############################################################################        
        url(r'^registerp4p_add.html$','blog.views.registerp4p_add'),
        url(r'^autop4p_add.html$','blog.views.autop4p_add'),
        url(r'^zzbsp4p_add.html$','blog.views.zzbsp4p_add'),
        url(r'^p4p_adddep_11.html$','blog.views.p4p_adddep_11'),
        url(r'^p4p_add.html$','blog.views.zzbsp4p_add'),
######################################################################
        url(r'^zzbsp4p_dlsproxy.html$',TemplateView.as_view(template_name="auto/zzbs-p4p_dlsproxy.html")),
        url(r'^registerp4p_dlsproxy.html$','blog.views.registerp4p_dlsproxy'),
        url(r'^p4p_dlsproxydep_11.html$','blog.views.p4p_dlsproxydep_11'),
        url(r'^p4p_dlsproxyhg_11.html$','blog.views.p4p_dlsproxyhg_11'),
        url(r'^p4p_dlsproxylog_11.html$','blog.views.p4p_dlsproxylog_11'),
#####################################################################
        url(r'^registercmsproxy_monitor.html$','blog.views.registercmsproxy_monitor'),
        url(r'^autocmsproxy_monitor.html$','blog.views.autocmsproxy_monitor'),
        url(r'^zzbscmsproxy_monitor.html$','blog.views.zzbscmsproxy_monitor'),
        url(r'^cmsproxy_monitordep_24.html$','blog.views.cmsproxy_monitordep_24'),
      #  url(r'^cmsproxy_monitor.html$','blog.views.cmsproxy_monitor'),
#######################################################################
        url(r'^dep-chaoji9918.html$','blog.views.chaoji99_18'),
        url(r'^dep-chaoji9919.html$','blog.views.chaoji99_19'),
        url(r'^dep-chaoji99121.html$','blog.views.chaoji99_121'),
        url(r'^zzbs-chaoji99.html$','blog.views.zzbschaoji99'),
        url(r'^register-chaoji99.html$','blog.views.registerchaoji99'),
        url(r'^auto-chaoji99.html$','blog.views.autochaoji99'),
#########################################################################
        url(r'^dep-chaoji99_i_121.html$','blog.views.chaoji99_i_121'),
        url(r'^dep-chaoji99_i_22.html$','blog.views.chaoji99_i_22'),
        url(r'^zzbs-chaoji99_i.html$','blog.views.zzbschaoji99_i'),
        url(r'^register-chaoji99_i.html$','blog.views.registerchaoji99_i'),
        url(r'^auto-chaoji99_i.html$','blog.views.autochaoji99_i'),
        url(r'^chaoji99.html$','blog.views.chaoji99'),
)
urlpatterns += patterns('',
        url(r'^dep-app9938.html$','blog.views.app99_38'),
        url(r'^dep-app9946.html$','blog.views.app99_46'),
        url(r'^zzbs-app99.html$','blog.views.zzbsapp99'),
        url(r'^register-app99.html$','blog.views.registerapp99'),
        url(r'^auto-app99.html$','blog.views.autoapp99'),
        url(r'^app99.html$','blog.views.app99'),
###############################################################
        url(r'^dep-qdtts_kmeye.html$','blog.views.registerqdtts_kmeyedep'),
        url(r'^dep-qdtts_kmeyedep_86.html$','blog.views.qdtts_kmeyedep_86'),
        url(r'^dep-qdtts_kmeyedep_7.html$','blog.views.qdtts_kmeyedep_7'),
        url(r'^zzbs-qdtts_kmeye.html$','blog.views.zzbtts_kmeyedep'),
        url(r'^cdn_kmeyedep_post.html$','blog.views.cdn_kmeyedep_post'),
############################################################################
        url(r'^registerqly.html$','blog.views.registerqly'),
    #    url(r'^autoqly.html$','blog.views.autoqly'),
        url(r'^zzbsqly.html$','blog.views.zzbsqly'),
        url(r'^qlydep_39.html$','blog.views.qlydep_39'),
	url(r'^qlydep_40.html$','blog.views.qlydep_40'),
        url(r'^qlyhg_39.html$','blog.views.qlyhg_39'),
        url(r'^qlyhg_40.html$','blog.views.qlyhg_40'),
        url(r'^qlylog_39.html$','blog.views.qlylog_39'),
        url(r'^qlylog_40.html$','blog.views.qlylog_40'),
        url(r'^qlydep_42.html$','blog.views.qlydep_42'),
        url(r'^qlyhg_42.html$','blog.views.qlyhg_42'),
        url(r'^qlylog_42.html$','blog.views.qlylog_42'),
        url(r'^qly_restart_39.html$','blog.views.qly_restart_39'),
        url(r'^qly_restart_40.html$','blog.views.qly_restart_40'),
        url(r'^qlyjavakill_42.html$','blog.views.qlyjavakill_42'),
####################################################################
        url(r'^dep-qdv7.html$','blog.views.registerqdv7dep'),
        url(r'^dep-qdv7dep_86.html$','blog.views.qdv7dep_86'),
        url(r'^dep-qdv7dep_7.html$','blog.views.qdv7dep_7'),
        url(r'^zzbs-qdv7.html$','blog.views.zzbv7dep'),
        url(r'^cdn_qdv7_post.html$','blog.views.cdn_qdv7_post'),
##################################################################
        url(r'^registersso.html$','blog.views.registersso'),
        #url(r'^autosso.html$','blog.views.autosso'),
        url(r'^zzbssso.html$','blog.views.zzbssso'),
        url(r'^ssodep_33.html$','blog.views.ssodep_33'),
        url(r'^ssohg_33.html$','blog.views.ssohg_33'),
        url(r'^ssolog_33.html$','blog.views.ssolog_33'),
        url(r'^ssodep_34.html$','blog.views.ssodep_34'),
        url(r'^ssohg_34.html$','blog.views.ssohg_33'),
        url(r'^ssolog_34.html$','blog.views.ssolog_34'),
        url(r'^sso.html$','blog.views.sso'),
###########################################################
#        url(r'^registerlsjpassport.html$','blog.views.registerlsjpassport'),
#        url(r'^autolsjpassport.html$','blog.views.autolsjpassport'),
#        url(r'^zzbslsjpassport.html$','blog.views.zzbslsjpassport'),
#        url(r'^lsjpassportdep_33.html$','blog.views.lsjpassportdep_33'),
#        url(r'^lsjpassportdep_34.html$','blog.views.lsjpassportdep_34'),
#     #   url(r'^lsjpassport.html$','blog.views.lsjpassport'),
################################################################
        url(r'^registerchaoji99passport.html$','blog.views.registerchaoji99passport'),
        url(r'^autochaoji99passport.html$','blog.views.autochaoji99passport'),
        url(r'^zzbschaoji99passport.html$','blog.views.zzbschaoji99passport'),
        url(r'^chaoji99passportdep_33.html$','blog.views.chaoji99passportdep_33'),
        url(r'^chaoji99passportdep_34.html$','blog.views.chaoji99passportdep_34'),

#        url(r'^dep-lingshijia_i_41.html$','blog.views.lingshijia_i_41'),
#        url(r'^dep-lingshijia_i_42.html$','blog.views.lingshijia_i_42'),
#        url(r'^zzbs-lingshijia_i.html$','blog.views.zzbslingshijia_i'),
#        url(r'^register-lingshijia_i.html$','blog.views.registerlingshijia_i'),
#        url(r'^auto-lingshijia_i.html$','blog.views.autolingshijia_i'),
#       # url(r'^lingshijia.html$','blog.views.lingshijia'),
##################################################################################
#        url(r'^dep-lingshijia_m_41.html$','blog.views.lingshijia_m_41'),
#        url(r'^dep-lingshijia_m_42.html$','blog.views.lingshijia_m_42'),
#        url(r'^zzbs-lingshijia_m.html$','blog.views.zzbslingshijia_m'),
#        url(r'^register-lingshijia_m.html$','blog.views.registerlingshijia_m'),
#        url(r'^auto-lingshijia_m.html$','blog.views.autolingshijia_m'),
#       # url(r'^lingshijia.html$','blog.views.lingshijia'),
#
#        url(r'^dep-lingshijia_cms_106.html$','blog.views.lingshijia_cms_106'),
#        url(r'^zzbs-lingshijia_cms.html$','blog.views.zzbslingshijia_cms'),
#        url(r'^register-lingshijia_cms.html$','blog.views.registerlingshijia_cms'),
#        url(r'^auto-lingshijia_cms.html$','blog.views.autolingshijia_cms'),
#        url(r'^dep-lingshijia_cmsproxy_43.html$','blog.views.lingshijia_cmsproxy_43'),
#        url(r'^dep-lingshijia_cmsproxy_44.html$','blog.views.lingshijia_cmsproxy_44'),
#        url(r'^zzbs-lingshijia_cmsproxy.html$','blog.views.zzbslingshijia_cmsproxy'),
#        url(r'^register-lingshijia_cmsproxy.html$','blog.views.registerlingshijia_cmsproxy'),
#        url(r'^auto-lingshijia_cmsproxy.html$','blog.views.autolingshijia_cmsproxy'),

#        url(r'^dep-qdqdlsjm.html$','blog.views.registerqdqdlsjmdep'),
#        url(r'^dep-qdqdlsjmdep_86.html$','blog.views.qdqdlsjmdep_86'),
#        url(r'^dep-qdqdlsjmdep_7.html$','blog.views.qdqdlsjmdep_7'),
#        url(r'^zzbs-qdlsjm.html$','blog.views.zzbsqdlsjmdep'),
        url(r'^dep-lsjsso.html$','blog.views.registerlsjssodep'),
        url(r'^auto-lsjsso.html$','blog.views.autolsj_sso'),
        url(r'^dep-lsjssodep_106.html$','blog.views.lsjssodep_106'),
        url(r'^zzbs-lsjsso.html$','blog.views.zzbslsjssodep'),
#################################################################################
#        url(r'^dep-qdtts_lingshijia.html$','blog.views.registerqdtts_lingshijiadep'),
#        url(r'^dep-qdtts_lingshijiadep_86.html$','blog.views.qdtts_lingshijiadep_86'),
#        url(r'^dep-qdtts_lingshijiadep_7.html$','blog.views.qdtts_lingshijiadep_7'),
#        url(r'^zzbs-qdtts_lingshijia.html$','blog.views.zzbtts_lingshijiadep'),
#
#        url(r'^dep-lsjwww.html$','blog.views.registerlsjwwwdep'),
#        url(r'^auto-lsjwww.html$','blog.views.autolsj_www'),
#        url(r'^dep-lsjwwwdep_45.html$','blog.views.lsjwwwdep_45'),
#        url(r'^dep-lsjwwwdep_46.html$','blog.views.lsjwwwdep_46'),
#        url(r'^zzbs-lsjwww.html$','blog.views.zzbslsjwwwdep'),
#        url(r'^lsjlinshi164.html$','blog.views.lsjlinshi164'),
#####################################################################################
        url(r'^moldcp.html$','blog.views.moldcp'),
        url(r'^moldauto.html$','blog.views.moldauto'),
        url(r'^appcp.html$','blog.views.appcp'),
        url(r'^appauto.html$','blog.views.appauto'),
        url(r'^engcp.html$','blog.views.engcp'),
        url(r'^engauto.html$','blog.views.engauto'),
        url(r'^moldzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-mold.html")),

        url(r'^moldep_12.html$','blog.views.moldep_12'),
        url(r'^moldhg_12.html$','blog.views.moldhg_12'),
        url(r'^moldlog_12.html$','blog.views.moldlog_12'),
        url(r'^moldep_13.html$','blog.views.moldep_13'),
        url(r'^moldhg_13.html$','blog.views.moldhg_13'),
        url(r'^moldlog_13.html$','blog.views.moldlog_13'),
        url(r'^moldep_14.html$','blog.views.moldep_14'),
        url(r'^moldhg_14.html$','blog.views.moldhg_14'),
        url(r'^moldlog_14.html$','blog.views.moldlog_14'),
        url(r'^moldep_24.html$','blog.views.moldep_24'),
        url(r'^moldhg_24.html$','blog.views.moldhg_24'),
        url(r'^moldlog_24.html$','blog.views.moldlog_24'),
        url(r'^moldep_25.html$','blog.views.moldep_25'),
        url(r'^moldhg_25.html$','blog.views.moldhg_25'),
        url(r'^moldlog_25.html$','blog.views.moldlog_25'),
        url(r'^moldep_29.html$','blog.views.moldep_29'),
        url(r'^moldhg_29.html$','blog.views.moldhg_29'),
        url(r'^moldlog_29.html$','blog.views.moldlog_29'),
        url(r'^moldep_32.html$','blog.views.moldep_32'),
        url(r'^moldhg_32.html$','blog.views.moldhg_32'),
        url(r'^moldlog_32.html$','blog.views.moldlog_32'),
#        url(r'^moldep_181.html$','blog.views.moldep_181'),
#        url(r'^moldhg_181.html$','blog.views.moldhg_181'),
#        url(r'^moldlog_181.html$','blog.views.moldlog_181'),
#        url(r'^moldep_65.html$','blog.views.moldep_65'),
#        url(r'^moldhg_65.html$','blog.views.moldhg_65'),
   #     url(r'^moldlog_65.html$','blog.views.moldlog_65'),
        url(r'^moldep_8.html$','blog.views.moldep_8'),
        url(r'^moldhg_8.html$','blog.views.moldhg_8'),
        url(r'^moldlog_8.html$','blog.views.moldlog_8'),
     #   url(r'^moldep_174.html$','blog.views.moldep_174'),
     #   url(r'^moldhg_174.html$','blog.views.moldhg_174'),
     #   url(r'^moldlog_174.html$','blog.views.moldlog_174'),
     #   url(r'^moldep_175.html$','blog.views.moldep_175'),
     #   url(r'^moldhg_175.html$','blog.views.moldhg_175'),
     #   url(r'^moldlog_175.html$','blog.views.moldlog_175'),
        url(r'^appep_12.html$','blog.views.appep_12'),
        url(r'^apphg_12.html$','blog.views.apphg_12'),
        url(r'^applog_12.html$','blog.views.applog_12'),
        url(r'^appep_13.html$','blog.views.appep_13'),
        url(r'^apphg_13.html$','blog.views.apphg_13'),
        url(r'^applog_13.html$','blog.views.applog_13'),
        url(r'^appep_14.html$','blog.views.appep_14'),
        url(r'^apphg_14.html$','blog.views.apphg_14'),
        url(r'^applog_14.html$','blog.views.applog_14'),
#        url(r'^appep_181.html$','blog.views.appep_181'),
#        url(r'^apphg_181.html$','blog.views.apphg_181'),
#        url(r'^applog_181.html$','blog.views.applog_181'),
        url(r'^appep_68.html$','blog.views.appep_68'),
        url(r'^apphg_68.html$','blog.views.apphg_68'),
        url(r'^applog_68.html$','blog.views.applog_68'),
	url(r'^appep_85.html$','blog.views.appep_85'),
        url(r'^apphg_85.html$','blog.views.apphg_85'),
        url(r'^applog_85.html$','blog.views.applog_85'),
        url(r'^appep_82.html$','blog.views.appep_82'),
        url(r'^apphg_82.html$','blog.views.apphg_82'),
        url(r'^applog_82.html$','blog.views.applog_82'),

        url(r'^appep_97.html$','blog.views.appep_97'),
        url(r'^apphg_97.html$','blog.views.apphg_97'),
        url(r'^applog_97.html$','blog.views.applog_97'),

#        url(r'^appep_160.html$','blog.views.appep_160'),
#        url(r'^apphg_160.html$','blog.views.apphg_160'),
#        url(r'^applog_160.html$','blog.views.applog_160'),
#
#        url(r'^appep_161.html$','blog.views.appep_161'),
#        url(r'^apphg_161.html$','blog.views.apphg_161'),
#        url(r'^applog_161.html$','blog.views.applog_161'),
#

        url(r'^engdep_12.html$','blog.views.engdep_12'),
        url(r'^enghg_12.html$','blog.views.enghg_12'),
        url(r'^englog_12.html$','blog.views.englog_12'),
        url(r'^engdep_13.html$','blog.views.engdep_13'),
        url(r'^enghg_13.html$','blog.views.enghg_13'),
        url(r'^englog_13.html$','blog.views.englog_13'),
        url(r'^engdep_14.html$','blog.views.engdep_14'),
        url(r'^enghg_14.html$','blog.views.enghg_14'),
        url(r'^englog_14.html$','blog.views.englog_14'),
#        url(r'^engdep_181.html$','blog.views.engdep_181'),
#        url(r'^enghg_181.html$','blog.views.enghg_181'),
#        url(r'^englog_181.html$','blog.views.englog_181'),
        url(r'^engdep_85.html$','blog.views.engdep_85'),
        url(r'^enghg_85.html$','blog.views.enghg_85'),
        url(r'^englog_85.html$','blog.views.englog_85'),
        url(r'^engdep_82.html$','blog.views.engdep_82'),
        url(r'^enghg_82.html$','blog.views.enghg_82'),
        url(r'^englog_82.html$','blog.views.englog_82'),
 #       url(r'^engdep_174.html$','blog.views.engdep_174'),
  #      url(r'^enghg_174.html$','blog.views.enghg_174'),
  #      url(r'^englog_174.html$','blog.views.englog_174'),
 #       url(r'^engdep_175.html$','blog.views.engdep_175'),
 #       url(r'^enghg_175.html$','blog.views.enghg_175'),
 #       url(r'^englog_175.html$','blog.views.englog_175'),
        url(r'^engdep_23.html$','blog.views.engdep_23'),
        url(r'^enghg_23.html$','blog.views.enghg_23'),
        url(r'^englog_23.html$','blog.views.englog_23'),
        url(r'^engdep_26.html$','blog.views.engdep_26'),
        url(r'^enghg_26.html$','blog.views.enghg_26'),
        url(r'^englog_26.html$','blog.views.englog_26'),
#        url(r'^engdep_8.html$','blog.views.engdep_8'),
#        url(r'^enghg_8.html$','blog.views.enghg_8'),
#        url(r'^englog_8.html$','blog.views.englog_8'),
        url(r'^zzbs-exttaobao.html$',TemplateView.as_view(template_name="auto/zzbs-exttaobao.html")),
        url(r'^zzbs-exttmt.html$',TemplateView.as_view(template_name="auto/zzbs-exttmt.html")),
        url(r'^dep-exttaobao.html$','blog.views.registerexttaobaodep'),
        url(r'^dep-exttmt.html$','blog.views.registerexttmtdep'),
        url(r'^dep-ext_taobao_13.html$','blog.views.ext_taobao_13'),
        url(r'^cdn_exttaobao_post.html$','blog.views.cdn_exttaobao_post'),
        url(r'^dep-ext_tmt_13.html$','blog.views.ext_tmt_13'),
        url(r'^cdn_exttmt_post.html$','blog.views.cdn_exttmt_post'),
        url(r'^zzbs-extstaobao.html$',TemplateView.as_view(template_name="auto/zzbs-extstaobao.html")),
        url(r'^zzbs-extstmt.html$',TemplateView.as_view(template_name="auto/zzbs-extstmt.html")),
        url(r'^dep-extstaobao.html$','blog.views.registerextstaobaodep'), 
        url(r'^dep-extstmt.html$','blog.views.registerextstmtdep'),
        url(r'^dep-exts_taobao_13.html$','blog.views.exts_taobao_13'),
        url(r'^dep-exts_tmt_13.html$','blog.views.exts_tmt_13'),

        url(r'^haolingzuicp.html$','blog.views.haolingzuicp'),
        url(r'^haolingzuiauto.html$','blog.views.haolingzuiauto'),
        url(r'^haolingzuizzbs.html$',TemplateView.as_view(template_name="auto/zzbs-haolingzui.html")),
        url(r'^haolingzuidep_91.html$','blog.views.haolingzuidep_91'),
        url(r'^haolingzuihg_91.html$','blog.views.haolingzuihg_91'),
        url(r'^haolingzuilog_91.html$','blog.views.haolingzuilog_91'),
        url(r'^haolingzuidep_44.html$','blog.views.haolingzuidep_44'),
        url(r'^haolingzuihg_44.html$','blog.views.haolingzuihg_44'),
        url(r'^haolingzuilog_44.html$','blog.views.haolingzuilog_44'),
        url(r'^zzbs-sp.html$',TemplateView.as_view(template_name="auto/zzbs-sp.html")),
        url(r'^spcp.html$','blog.views.spcp'),
	url(r'^spdep187.html$','blog.views.spdep_187'),
#	url(r'^spdep193.html$','blog.views.spdep_193'),
#	url(r'^spdep194.html$','blog.views.spdep_194'),
#	url(r'^spdep204.html$','blog.views.spdep_204'),
	url(r'^spdep225.html$','blog.views.spdep_225'),
	url(r'^spdep226.html$','blog.views.spdep_226'),
	url(r'^spdep227.html$','blog.views.spdep_227'),
	url(r'^spdep228.html$','blog.views.spdep_228'),
	url(r'^spdep229.html$','blog.views.spdep_229'),
#	url(r'^spdep207.html$','blog.views.spdep_207'),
	url(r'^spdep190.html$','blog.views.spdep_190'),
        url(r'^spdep199.html$','blog.views.spdep_199'),
        url(r'^sp.html$','blog.views.sp'),

        url(r'^qdhlzmdep86.html$','blog.views.qdhlzmdep_86'),
        url(r'^qdhlzmdep7.html$','blog.views.qdhlzmdep_7'),
        url(r'^qdhlz.html$','blog.views.registerqdhlz'),
	url(r'^zzbs-qdhlz.html$',TemplateView.as_view(template_name="auto/zzbs-qdhlz.html")),

	url(r'^mlz_m_A13.html$','blog.views.mlz_m_A13'),
       
        url(r'^registsb.html$','blog.views.registsb'),
        url(r'^mlz_sb_A13.html$','blog.views.mlz_sb_A13'),
 
        url(r'^zzbs-qdbd.html$','blog.views.registbd'),
        url(r'^tts_bd_A13.html$','blog.views.tts_bd_A13'),

        url(r'^zzbs-qdbdtest.html$','blog.views.registbdtest'),
        url(r'^tts_bd_A13test.html$','blog.views.tts_bd_A13test'),

        url(r'^hlz_seckillzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_seckill.html")),
        url(r'^hlz_seckillcp.html$','blog.views.hlz_seckillcp'),
        #url(r'^hlz_seckillauto.html$','blog.views.hlz_seckillauto'),
        url(r'^hlz_seckilldep_49.html$','blog.views.hlz_seckilldep_49'),
        url(r'^hlz_seckillhg_49.html$','blog.views.hlz_seckillhg_49'),
        url(r'^hlz_seckilllog_49.html$','blog.views.hlz_seckilllog_49'),
        url(r'^hlz_seckilldep_42.html$','blog.views.hlz_seckilldep_42'),
        url(r'^hlz_seckillhg_42.html$','blog.views.hlz_seckillhg_42'),
        url(r'^hlz_seckilllog_42.html$','blog.views.hlz_seckilllog_42'),
        url(r'^hlz_tradezzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_trade.html")),
        url(r'^hlz_tradecp.html$','blog.views.hlz_tradecp'),
        #url(r'^hlz_tradeauto.html$','blog.views.hlz_tradeauto'),
        url(r'^hlz_tradedep_49.html$','blog.views.hlz_tradedep_49'),
        url(r'^hlz_tradelog_49.html$','blog.views.hlz_tradelog_49'),
	url(r'^hlz_tradehg_49.html$','blog.views.hlz_tradehg_49'),
        url(r'^hlz_tradedep_91.html$','blog.views.hlz_tradedep_91'),
        url(r'^hlz_tradelog_91.html$','blog.views.hlz_tradelog_91'),
        url(r'^hlz_tradehg_91.html$','blog.views.hlz_tradehg_91'),
	url(r'^hlz_cmsproxyzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_cmsproxy.html")),
        url(r'^hlz_cmsproxycp.html$','blog.views.hlz_cmsproxycp'),
        #url(r'^hlz_cmsproxyauto.html$','blog.views.hlz_cmsproxyauto'),
        url(r'^hlz_cmsproxydep_49.html$','blog.views.hlz_cmsproxydep_49'),
        url(r'^hlz_cmsproxylog_49.html$','blog.views.hlz_cmsproxylog_49'),
	url(r'^hlz_cmsproxyhg_49.html$','blog.views.hlz_cmsproxyhg_49'),
        url(r'^hlz_cmsproxydep_91.html$','blog.views.hlz_cmsproxydep_91'),
        url(r'^hlz_cmsproxylog_91.html$','blog.views.hlz_cmsproxylog_91'),
        url(r'^hlz_cmsproxyhg_91.html$','blog.views.hlz_cmsproxyhg_91'),
        url(r'^hlz_cmsproxydep_19.html$','blog.views.hlz_cmsproxydep_19'),
        url(r'^hlz_cmsproxylog_19.html$','blog.views.hlz_cmsproxylog_19'),
        url(r'^hlz_cmsproxyhg_19.html$','blog.views.hlz_cmsproxyhg_19'),
        url(r'^hlz_cmsproxydep_33.html$','blog.views.hlz_cmsproxydep_33'),
        url(r'^hlz_cmsproxylog_33.html$','blog.views.hlz_cmsproxylog_33'),
        url(r'^hlz_cmsproxyhg_33.html$','blog.views.hlz_cmsproxyhg_33'),


        url(r'^hlz_payzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_pay.html")),
        url(r'^hlz_paycp.html$','blog.views.hlz_paycp'),
        #url(r'^hlz_payauto.html$','blog.views.hlz_payauto'),
        url(r'^hlz_paydep_64.html$','blog.views.hlz_paydep_64'),
        url(r'^hlz_paylog_64.html$','blog.views.hlz_paylog_64'),
        url(r'^hlz_payhg_64.html$','blog.views.hlz_payhg_64'),
        url(r'^hlz_paydep_46.html$','blog.views.hlz_paydep_46'),
        url(r'^hlz_paylog_46.html$','blog.views.hlz_paylog_46'),
        url(r'^hlz_payhg_46.html$','blog.views.hlz_payhg_46'),

    )
urlpatterns += patterns('',
        url(r'^hlz_passportzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_passport.html")),
        url(r'^hlz_passportcp.html$','blog.views.hlz_passportcp'),
        #url(r'^hlz_passportauto.html$','blog.views.hlz_passportauto'),
        url(r'^hlz_passportdep_64.html$','blog.views.hlz_passportdep_64'),
        url(r'^hlz_passportlog_64.html$','blog.views.hlz_passportlog_64'),
        url(r'^hlz_passporthg_64.html$','blog.views.hlz_passporthg_64'),
        url(r'^hlz_passportdep_91.html$','blog.views.hlz_passportdep_91'),
        url(r'^hlz_passportlog_91.html$','blog.views.hlz_passportlog_91'),
        url(r'^hlz_passporthg_91.html$','blog.views.hlz_passporthg_91'),
        url(r'^hlz_sellerzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_seller.html")),
        url(r'^hlz_sellercp.html$','blog.views.hlz_sellercp'),
        #url(r'^hlz_sellerauto.html$','blog.views.hlz_sellerauto'),
        url(r'^hlz_sellerdep_64.html$','blog.views.hlz_sellerdep_64'),
        url(r'^hlz_sellerlog_64.html$','blog.views.hlz_sellerlog_64'),
        url(r'^hlz_sellerhg_64.html$','blog.views.hlz_sellerhg_64'),
        url(r'^hlz_sellerdep_91.html$','blog.views.hlz_sellerdep_91'),
        url(r'^hlz_sellerlog_91.html$','blog.views.hlz_sellerlog_91'),
        url(r'^hlz_sellerhg_91.html$','blog.views.hlz_sellerhg_91'),


        url(r'^hlz_sellerdep_18.html$','blog.views.hlz_sellerdep_18'),
        url(r'^hlz_sellerlog_18.html$','blog.views.hlz_sellerlog_18'),
        url(r'^hlz_sellerhg_18.html$','blog.views.hlz_sellerhg_18'),

        url(r'^hlz_cmszzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_cms.html")),
        url(r'^hlz_cmscp.html$','blog.views.hlz_cmscp'),
        url(r'^hlz_cmsdep_106.html$','blog.views.hlz_cmsdep_106'),
        url(r'^hlz_cmslog_106.html$','blog.views.hlz_cmslog_106'),
        url(r'^hlz_cmshg_106.html$','blog.views.hlz_cmshg_106'),
        url(r'^hlz_mzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_m.html")),
        url(r'^hlz_mcp.html$','blog.views.hlz_mcp'),
        #url(r'^hlz_mauto.html$','blog.views.hlz_mauto'),
        url(r'^hlz_mdep_64.html$','blog.views.hlz_mdep_64'),
        url(r'^hlz_mlog_64.html$','blog.views.hlz_mlog_64'),
        url(r'^hlz_mhg_64.html$','blog.views.hlz_mhg_64'),
        url(r'^hlz_mdep_91.html$','blog.views.hlz_mdep_91'),
        url(r'^hlz_mlog_91.html$','blog.views.hlz_mlog_91'),
        url(r'^hlz_mhg_91.html$','blog.views.hlz_mhg_91'),

        url(r'^qly_pluginzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-qly_plugin.html")),
        url(r'^qly_plugincp.html$','blog.views.qly_plugincp'),
        url(r'^qly_plugindep_32.html$','blog.views.qly_plugindep_32'),
        url(r'^qly_pluginlog_32.html$','blog.views.qly_pluginlog_32'),
        url(r'^qly_pluginhg_32.html$','blog.views.qly_pluginhg_32'),
        url(r'^qly_plugindep_36.html$','blog.views.qly_plugindep_36'),
        url(r'^qly_pluginlog_36.html$','blog.views.qly_pluginlog_36'),
        url(r'^qly_pluginhg_36.html$','blog.views.qly_pluginhg_36'),
        url(r'^qly_plugindep_80.html$','blog.views.qly_plugindep_80'),
        url(r'^qly_pluginlog_80.html$','blog.views.qly_pluginlog_80'),
        url(r'^qly_pluginhg_80.html$','blog.views.qly_pluginhg_80'),
        url(r'^qly_plugindep_23.html$','blog.views.qly_plugindep_23'),
        url(r'^qly_pluginlog_23.html$','blog.views.qly_pluginlog_23'),
        url(r'^qly_pluginhg_23.html$','blog.views.qly_pluginhg_23'),
        url(r'^qly_pluginrestart_32.html$','blog.views.qly_pluginrestart_32'),
        url(r'^qly_pluginrestart_36.html$','blog.views.qly_pluginrestart_36'),
        url(r'^qly_pluginrestart_80.html$','blog.views.qly_pluginrestart_80'),
        url(r'^qly_pluginrestart_23.html$','blog.views.qly_pluginrestart_23'),

        url(r'^hlz_lotteryzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_lottery.html")),
        url(r'^hlz_lotterycp.html$','blog.views.hlz_lotterycp'),
        url(r'^hlz_lotterydep_17.html$','blog.views.hlz_lotterydep_17'),
        url(r'^hlz_lotterylog_17.html$','blog.views.hlz_lotterylog_17'),
        url(r'^hlz_lotteryhg_17.html$','blog.views.hlz_lotteryhg_17'),
        url(r'^hlz_lotterydep_18.html$','blog.views.hlz_lotterydep_18'),
        url(r'^hlz_lotterylog_18.html$','blog.views.hlz_lotterylog_18'),
        url(r'^hlz_lotteryhg_18.html$','blog.views.hlz_lotteryhg_18'),

        url(r'^brzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-br.html")),
        url(r'^brcp.html$','blog.views.brcp'),
        url(r'^brdep1_183.html$','blog.views.brdep1_183'),
        url(r'^bjrestart_183.html$','blog.views.bjrestart_183'),
#        url(r'^brdep2_183.html$','blog.views.brdep2_183'),
#        url(r'^brdep3_183.html$','blog.views.brdep3_183'),
#	url(r'^brdep4_183.html$','blog.views.brdep4_183'),
        url(r'^brdep1_94.html$','blog.views.brdep1_94'),
        url(r'^bjrestart_94.html$','blog.views.bjrestart_94'),
#        url(r'^brdep2_94.html$','blog.views.brdep2_94'),
#	url(r'^brdep3_94.html$','blog.views.brdep3_94'),		
        url(r'^brdep1_83.html$','blog.views.brdep1_83'),
        url(r'^bjrestart_83.html$','blog.views.bjrestart_83'),
#        url(r'^brdep2_83.html$','blog.views.brdep2_83'),
#	url(r'^brdep3_83.html$','blog.views.brdep3_83'),	
        url(r'^brdep1_48.html$','blog.views.brdep1_48'),
        url(r'^bjrestart_48.html$','blog.views.bjrestart_48'),
#        url(r'^brdep2_48.html$','blog.views.brdep2_48'),
#	url(r'^brdep3_48.html$','blog.views.brdep3_48'),		
        url(r'^brdep1_51.html$','blog.views.brdep1_51'),
        url(r'^bjrestart_51.html$','blog.views.bjrestart_51'),
#        url(r'^brdep2_51.html$','blog.views.brdep2_51'),
#	url(r'^brdep3_51.html$','blog.views.brdep3_51'),
#        url(r'^zzbs-bexttaobao.html$',TemplateView.as_view(template_name="auto/zzbs-bexttaobao.html")),
#        url(r'^dep-bexttaobao.html$','blog.views.registerbexttaodep'),
#        url(r'^dep-bext_taobao_13.html$','blog.views.bext_tao_13'),

#        url(r'^zzbs-bextstaobao.html$',TemplateView.as_view(template_name="auto/zzbs-bextstaobao.html")),
#        url(r'^dep-bextstaobao.html$','blog.views.registerbextstaodep'),
#        url(r'^dep-bexts_taobao_13.html$','blog.views.bexts_tao_13'),
        url(r'^qly_bbszzbs.html$',TemplateView.as_view(template_name="auto/zzbs-qly_bbs.html")),
        url(r'^qly_bbscp.html$','blog.views.qly_bbscp'),
        url(r'^qly_bbsdep_39.html$','blog.views.qly_bbsdep_39'),
        url(r'^qly_bbslog_39.html$','blog.views.qly_bbslog_39'),
        url(r'^qly_bbshg_39.html$','blog.views.qly_bbshg_39'),
        url(r'^qly_bbsdep_40.html$','blog.views.qly_bbsdep_40'),
        url(r'^qly_bbslog_40.html$','blog.views.qly_bbslog_40'),
        url(r'^qly_bbshg_40.html$','blog.views.qly_bbshg_40'),

        url(r'^p4p_ipzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-p4p_ip.html")),
        url(r'^p4p_ipcp.html$','blog.views.p4p_ipcp'),
        url(r'^p4p_ipdep_48.html$','blog.views.p4p_ipdep_48'),
        url(r'^p4p_iplog_48.html$','blog.views.p4p_iplog_48'),
        url(r'^p4p_iphg_48.html$','blog.views.p4p_iphg_48'),
        url(r'^p4p_ipdep_94.html$','blog.views.p4p_ipdep_94'),
        url(r'^p4p_iplog_94.html$','blog.views.p4p_iplog_94'),
        url(r'^p4p_iphg_94.html$','blog.views.p4p_iphg_94'),

        url(r'^zzbs-wylm.html$',TemplateView.as_view(template_name="auto/zzbs-wylm.html")),
        url(r'^dep-wylm.html$','blog.views.registerwylmdep'),
        url(r'^dep-wylm_13.html$','blog.views.wylm_13'),
        url(r'^cdn_wylm_post.html$','blog.views.cdn_wylm_post'),

        url(r'^zzbs-wylms.html$',TemplateView.as_view(template_name="auto/zzbs-wylms.html")),
        url(r'^dep-wylms.html$','blog.views.registerwylmsdep'),
        url(r'^dep-wylms_13.html$','blog.views.wylms_13'),

        url(r'^hlz_scorezzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_score.html")),
        url(r'^hlz_scorecp.html$','blog.views.hlz_scorecp'),
        url(r'^hlz_scoredep_91.html$','blog.views.hlz_scoredep_91'),
        url(r'^hlz_scorelog_91.html$','blog.views.hlz_scorelog_91'),
        url(r'^hlz_scorehg_91.html$','blog.views.hlz_scorehg_91'),
        url(r'^hlz_scoredep_42.html$','blog.views.hlz_scoredep_42'),
        url(r'^hlz_scorelog_42.html$','blog.views.hlz_scorelog_42'),
        url(r'^hlz_scorehg_42.html$','blog.views.hlz_scorehg_42'),

        url(r'^hlz_rewardzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_reward.html")),
        url(r'^hlz_rewardcp.html$','blog.views.hlz_rewardcp'),
        url(r'^hlz_rewarddep_91.html$','blog.views.hlz_rewarddep_91'),
        url(r'^hlz_rewardlog_91.html$','blog.views.hlz_rewardlog_91'),
        url(r'^hlz_rewardhg_91.html$','blog.views.hlz_rewardhg_91'),
        url(r'^hlz_rewarddep_42.html$','blog.views.hlz_rewarddep_42'),
        url(r'^hlz_rewardlog_42.html$','blog.views.hlz_rewardlog_42'),
        url(r'^hlz_rewardhg_42.html$','blog.views.hlz_rewardhg_42'),

        url(r'^zzbs-union.html$',TemplateView.as_view(template_name="auto/zzbs-union.html")),
        url(r'^dep-union.html$','blog.views.registeruniondep'),
        url(r'^dep-union_13.html$','blog.views.union_13'),

        url(r'^p4p_pubzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-p4p_pub.html")),
        url(r'^p4p_pubcp.html$','blog.views.p4p_pubcp'),
        url(r'^p4p_pubdep_81.html$','blog.views.p4p_pubdep_81'),
        url(r'^p4p_publog_81.html$','blog.views.p4p_publog_41'),
        url(r'^p4p_pubhg_81.html$','blog.views.p4p_pubhg_41'),

        url(r'^hlz_mqzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-hlz_mq.html")),
        url(r'^hlz_mqcp.html$','blog.views.hlz_mqcp'),
        url(r'^hlz_mqdep_91.html$','blog.views.hlz_mqdep_91'),
        url(r'^hlz_mqlog_91.html$','blog.views.hlz_mqlog_91'),
        url(r'^hlz_mqhg_91.html$','blog.views.hlz_mqhg_91'),

	url(r'^qly_extension.html$',TemplateView.as_view(template_name="auto/qly_extension.html")),
        url(r'^register_qly_extension.html$','blog.views.register_qly_extension'),
        url(r'^qly_extension_164.html$','blog.views.qly_extension_164'),

        url(r'^zzbs-qdtts_ad.html$',TemplateView.as_view(template_name="auto/zzbs-qdtts_ad.html")),
        url(r'^registertts_addep.html$','blog.views.registertts_addep'),
        url(r'^tts_ad_86.html$','blog.views.tts_ad_86'),
        url(r'^cdn_tts_ad_post.html$','blog.views.cdn_tts_ad_post'),

        url(r'^ad_mgrzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-ad_mgr.html")),
        url(r'^ad_mgrcp.html$','blog.views.registerad_mgrcp'),
        url(r'^ad_mgrdep_124.html$','blog.views.ad_mgrdep_124'),
        url(r'^ad_mgrlog_124.html$','blog.views.ad_mgrlog_124'),
        url(r'^ad_mgrhg_124.html$','blog.views.ad_mgrhg_124'),
        url(r'^ad_mgrrestart_124.html$','blog.views.ad_mgrrestart_124'),

        url(r'^ad-promotionzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-ad-promotion.html")),
        url(r'^ad-promotioncp.html$','blog.views.ad_promotioncp'),
        url(r'^ad-promotiondep_124.html$','blog.views.ad_promotiondep_124'),
        url(r'^ad-promotionlog_124.html$','blog.views.ad_promotionlog_124'),
        url(r'^ad-promotionhg_124.html$','blog.views.ad_promotionhg_124'),

        url(r'^salezzbs.html$',TemplateView.as_view(template_name="auto/zzbs-sale.html")),
        url(r'^salecp.html$','blog.views.salecp'),
        url(r'^saledep1_36.html$','blog.views.saledep1_36'),
	url(r'^saledep1_37.html$','blog.views.saledep1_37'),

        url(r'^sale_adminzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-sale_admin.html")),
        url(r'^sale_admincp.html$','blog.views.sale_admincp'),
        url(r'^sale_admindep1_36.html$','blog.views.sale_admindep1_36'),

        url(r'^zzbs-qly_findhuo.html$',TemplateView.as_view(template_name="auto/zzbs-qly_findhuo.html")),
        url(r'^registerqly_findhuo.html$','blog.views.registerqly_findhuo'),
        url(r'^zzbsqly_findhuo.html$','blog.views.zzbsqly_findhuo'),
        url(r'^qly_findhuodep_42.html$','blog.views.qly_findhuodep_42'),
        url(r'^qly_findhuodep_49.html$','blog.views.qly_findhuodep_49'),

        url(r'^checkip.html$','blog.views.CHECKIP'),

        url(r'^zzbs-qdfindhuo.html$',TemplateView.as_view(template_name="auto/zzbs-qdfindhuo.html")),
        url(r'^dep-qdfindhuo.html$','blog.views.registerqdfindhuodep'),
        url(r'^dep-qdqdfindhuodep_86.html$','blog.views.qdqdfindhuodep_86'),
        url(r'^zzbs-qdfindhuo.html$','blog.views.zzbsqdfindhuodep'),
        url(r'^cdn_qdfindhuo_post.html$','blog.views.cdn_qdfindhuo_post'),
        
        url(r'^zzbs-qdtk.html$',TemplateView.as_view(template_name="auto/zzbs-qdtk.html")),
        url(r'^dep-qdtk.html$','blog.views.registerqdtkdep'),
        url(r'^dep-qdtkdep_164.html$','blog.views.qdtkdep_164'),
        url(r'^zzbs-qdtk.html$','blog.views.zzbsqdtkdep'),	   
	url(r'^cdn_qdtk_post.html$','blog.views.cdn_qdtk_post'),
        url(r'^sip.html$','blog.views.SIP'),

        url(r'^qly_moneyzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-qly_money.html")),
        url(r'^qly_moneycp.html$','blog.views.qly_moneycp'),
        url(r'^qly_moneydep_23.html$','blog.views.qly_moneydep_23'),
        url(r'^qly_moneylog_23.html$','blog.views.qly_moneylog_23'),
        url(r'^qly_moneyhg_23.html$','blog.views.qly_moneyhg_23'),
        url(r'^qly_moneydep_25.html$','blog.views.qly_moneydep_25'),
        url(r'^qly_moneylog_25.html$','blog.views.qly_moneylog_25'),
        url(r'^qly_moneyhg_25.html$','blog.views.qly_moneyhg_25'),

        url(r'^zzbs-qdsjd.html$',TemplateView.as_view(template_name="auto/zzbs-qdsjd.html")),
        url(r'^dep-qdsjd.html$','blog.views.registerqdsjddep'),
        url(r'^dep-qdqdsjddep_86.html$','blog.views.qdqdsjddep_86'),

        url(r'^qly_weixinzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-qly_weixin.html")),
        url(r'^qly_weixincp.html$','blog.views.qly_weixincp'),
        url(r'^qly_weixindep_149.html$','blog.views.qly_weixindep_149'),
        url(r'^qly_weixinlog_149.html$','blog.views.qly_weixinlog_149'),
        url(r'^qly_weixinhg_149.html$','blog.views.qly_weixinhg_149'),

        url(r'^qly_datazzbs.html$',TemplateView.as_view(template_name="auto/zzbs-qly_data.html")),
        url(r'^qly_datacp.html$','blog.views.qly_datacp'),
        url(r'^qly_datadep_109.html$','blog.views.qly_datadep_109'),
        url(r'^qly_datalog_109.html$','blog.views.qly_datalog_109'),
        url(r'^qly_datahg_109.html$','blog.views.qly_datahg_109'),
        url(r'^qly_datadep_122.html$','blog.views.qly_datadep_122'),
        url(r'^qly_datalog_122.html$','blog.views.qly_datalog_122'),
        url(r'^qly_datahg_122.html$','blog.views.qly_datahg_122'),
	url(r'^qly_datadep_29.html$','blog.views.qly_datadep_29'),
        url(r'^qly_datalog_29.html$','blog.views.qly_datalog_29'),
        url(r'^qly_datahg_29.html$','blog.views.qly_datahg_29'),
	url(r'^qly_datadep_143.html$','blog.views.qly_datadep_143'),
        url(r'^qly_datalog_143.html$','blog.views.qly_datalog_143'),
        url(r'^qly_datahg_143.html$','blog.views.qly_datahg_143'),
        url(r'^zzbs-registextend.html$','blog.views.registextend'),
        url(r'^tts_extend_86.html$','blog.views.tts_extend_86'),
        url(r'^zzbs-qdcrm.html$',TemplateView.as_view(template_name="auto/zzbs-qdcrm.html")),
        url(r'^dep-qdcrm.html$','blog.views.registerqdcrmdep'),
        url(r'^dep-qdqdcrmdep_86.html$','blog.views.qdqdcrmdep_86'),
        url(r'^qly_scorezzbs.html$',TemplateView.as_view(template_name="auto/zzbs-qly_score.html")),
        url(r'^qly_scorecp.html$','blog.views.qly_scorecp'),
        url(r'^qly_scoredep_33.html$','blog.views.qly_scoredep_33'),
        url(r'^qly_scorelog_33.html$','blog.views.qly_scorelog_33'),
        url(r'^qly_scorehg_33.html$','blog.views.qly_scorehg_33'),
        url(r'^qly_scoredep_34.html$','blog.views.qly_scoredep_34'),
        url(r'^qly_scorelog_34.html$','blog.views.qly_scorelog_34'),
        url(r'^qly_scorehg_34.html$','blog.views.qly_scorehg_34'),
   
        url(r'^zzbs-qdsb.html$','blog.views.registsb'),
        url(r'^tts_sb_203.html$','blog.views.tts_sb_203'),
        url(r'^zzbs-registwydown.html$', 'blog.views.registwydown'),
        url(r'^tts_wydown_86.html$', 'blog.views.tts_wydown_86'),
        url(r'^weiyousb.html$', 'blog.views.weiyousb'),
        url(r'^weiyousbtest.html$', 'blog.views.weiyousbtest'),
        url(r'^qly_screenzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-qly_screen.html")),
        url(r'^qly_screencp.html$','blog.views.qly_screencp'),
        url(r'^qly_screendep_23.html$','blog.views.qly_screendep_23'),
        url(r'^qly_screenlog_23.html$','blog.views.qly_screenlog_23'),
        url(r'^qly_screenhg_23.html$','blog.views.qly_screenhg_23'),

        #url(r'^wy_wwwzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-wy_www.html")),
        url(r'^wy_wwwzzbs.html$','blog.views.wywwwlog'),
        url(r'^wy_wwwcp.html$','blog.views.wy_wwwcp'),
        url(r'^wy_wwwdep_65.html$','blog.views.wy_wwwdep_65'),
        url(r'^wy_wwwdep_72.html$','blog.views.wy_wwwdep_72'),

        url(r'^wy_socketzzbs.html$','blog.views.wysocketlog'),
        url(r'^wy_socketcp.html$','blog.views.socketcp'),
        url(r'^wy_socketdep_68.html$','blog.views.socketdep_68'),
        url(r'^wy_socketdep_74.html$','blog.views.socketdep_74'),
        url(r'^socketyz.html$','blog.views.socketyz'),

        url(r'^wy_pubzzbs.html$','blog.views.wy_publog'),
        url(r'^wy_pubcp.html$','blog.views.wy_pubcp'),
        url(r'^wy_pubdep_63.html$','blog.views.wy_pubdep_63'),
        url(r'^wy_pubdep_71.html$','blog.views.wy_pubdep_71'),
 
        url(r'^wy_backzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-wy_back.html")),
	url(r'^wy_backcp.html$','blog.views.wy_backcp'),
        url(r'^wy_backdep_124.html$','blog.views.wy_backdep_124'),
        url(r'^wy_backlog_124.html$','blog.views.wy_backlog_124'),
        url(r'^wy_backhg_124.html$','blog.views.wy_backhg_124'),
        url(r'^zzbs-spider.html$','blog.views.spider149log'),
        url(r'^spider149.html$','blog.views.spider149'),
        url(r'^spider149cp.html$','blog.views.spider149cp'),
        url(r'^spider149dep.html$','blog.views.spider149dep'),
        url(r'^zzbs-androiddl.html$','blog.views.androiddl'),
        url(r'^zzbs-extend.html$','blog.views.extend'),

        url(r'^opinionzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-opinion.html")),
        url(r'^opinioncp.html$','blog.views.opinioncp'),
        url(r'^opiniondep_13.html$','blog.views.opiniondep_13'),
        url(r'^opinionlog_13.html$','blog.views.opinionlog_13'),
        url(r'^opinionhg_13.html$','blog.views.opinionhg_13'),
        url(r'^opbackzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-opback.html")),
        url(r'^opbackcp.html$','blog.views.opbackcp'),
        url(r'^opbackdep_14.html$','blog.views.opbackdep_14'),
        url(r'^opbacklog_14.html$','blog.views.opbacklog_14'),
        url(r'^opbackhg_14.html$','blog.views.opbackhg_14'),
)
urlpatterns += patterns('',
        url(r'^qlymanagerzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-qlymanager.html")),
        url(r'^qlymanagercp.html$','blog.views.qlymanagercp'),
        url(r'^qlymanagerdep_50.html$','blog.views.qlymanagerdep_50'),
        url(r'^qlymanagerlog_50.html$','blog.views.qlymanagerlog_50'),
        url(r'^qlymanagerhg_50.html$','blog.views.qlymanagerhg_50'),
        url(r'^qly_restart_50.html$','blog.views.qly_restart_50'),
        url(r'^qlymanagerdep_51.html$','blog.views.qlymanagerdep_51'),
        url(r'^qlymanagerlog_51.html$','blog.views.qlymanagerlog_51'),
        url(r'^qlymanagerhg_51.html$','blog.views.qlymanagerhg_51'),
        url(r'^qly_restart_51.html$','blog.views.qly_restart_51'),

        url(r'^zzbs-yunkefu.html$',TemplateView.as_view(template_name="auto/zzbs-yunkefu.html")),
        url(r'^dep-yunkefu.html$','blog.views.registeryunkefudep'),
        url(r'^dep-qdyunkefudep_86.html$','blog.views.qdyunkefudep_86'),
        url(r'^weidiandqtest.html$', 'blog.views.weidiandqtest'),
        url(r'^weidiandq.html$', 'blog.views.weidiandq'),
        url(r'^windowsdl.html$','blog.views.windowsdl'),
        url(r'^turegist.html$','blog.views.turegist'),
        url(r'^videoup.html$','blog.views.videoup'),


        url(r'^spsellerzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-weishop_seller.html")),
        url(r'^spsellercp.html$','blog.views.spsellercp'),
        url(r'^spsellerdep_52.html$','blog.views.spsellerdep_52'),
        url(r'^spsellerlog_52.html$','blog.views.spsellerlog_52'),
        url(r'^spsellerhg_52.html$','blog.views.spsellerhg_52'),
        url(r'^spsellerdep_53.html$','blog.views.spsellerdep_53'),
        url(r'^spsellerlog_53.html$','blog.views.spsellerlog_53'),
        url(r'^spsellerhg_53.html$','blog.views.spsellerhg_53'),

        url(r'^shop_tpzzbs.html$',TemplateView.as_view(template_name="auto/zzbs-shop_tp.html")),
        url(r'^weishop_tp.html$','blog.views.weishop_tpregister'),
        url(r'^shop_tpdep_56.html$','blog.views.shop_tpdep_56'),
        url(r'^shop_tplog_56.html$','blog.views.shop_tplog_56'),
        url(r'^shop_tphg_56.html$','blog.views.shop_tphg_56'),
 
        url(r'^weishop_apizzbs.html$',TemplateView.as_view(template_name="auto/zzbs-weishop_api.html")),
        url(r'^weishop_apicp.html$','blog.views.weishop_apicp'),
        url(r'^weishop_apidep_54.html$','blog.views.weishop_apidep_54'),
        url(r'^weishop_apilog_54.html$','blog.views.weishop_apilog_54'),
        url(r'^weishop_apihg_54.html$','blog.views.weishop_apihg_54'),
        url(r'^weishop_apidep_55.html$','blog.views.weishop_apidep_55'),
        url(r'^weishop_apilog_55.html$','blog.views.weishop_apilog_55'),
        url(r'^weishop_apihg_55.html$','blog.views.weishop_apihg_55'),

        url(r'^zzbs-wsback.html$',TemplateView.as_view(template_name="auto/zzbs-wsback.html")),
        url(r'^dep-wsback.html$','blog.views.registerwsbackdep'),
        url(r'^dep-qdwsbackdep_86.html$','blog.views.qdwsbackdep_86'),

        url(r'^zzbs-qlyexon.html$',TemplateView.as_view(template_name="auto/zzbs-qlyexon.html")),
        url(r'^dep-qlyexon.html$','blog.views.registerqlyexondep'),
        url(r'^dep-qdqlyexondep_86.html$','blog.views.qdqlyexondep_86'),
        url(r'^youcheqd.html$', 'blog.views.youcheqd'),

        url(r'^zzbs-qlyyouche.html$',TemplateView.as_view(template_name="auto/zzbs-qlyyouche.html")),
        url(r'^dep-qlyyouche.html$','blog.views.registerqlyyouchedep'),
        url(r'^dep-qdqlyyouchedep_86.html$','blog.views.qdqlyyouchedep_86'),
        url(r'^tus.html$','blog.views.tus'),

        url(r'^zzbs-qly_title.html$',TemplateView.as_view(template_name="auto/zzbs-qly_title.html")),
        url(r'^registerqly_title.html$','blog.views.registerqly_title'),
        #url(r'^zzbsqly_title.html$','blog.views.zzbsqly_title'),
        url(r'^qly_titledep_123.html$','blog.views.qly_titledep_123'),
        url(r'^qly_titledep_125.html$','blog.views.qly_titledep_125'),
	url(r'^qly_titledep_127.html$','blog.views.qly_titledep_127'),

        url(r'^zzbs-ceshitext.html$',TemplateView.as_view(template_name="auto/zzbs-ceshitext.html")),
        url(r'^dep-ceshitext.html$','blog.views.registerceshitextdep'),
        url(r'^dep-qdceshitextdep_86.html$','blog.views.qdceshitextdep_86'),

)
